name: wanted
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.6 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^5.1.0
  device_preview: ^1.1.0
  dotted_border: ^2.1.0
  flutter_staggered_grid_view: 0.7.0
  carousel_slider: ^4.0.0
  qr_code_scanner:
  vibration: ^1.7.1
  http:



  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/LatoRegular.ttf
          weight: 400
    - family: Quicksand
      fonts:
        - asset: assets/fonts/QuicksandSemiBold.ttf
          weight: 600
        - asset: assets/fonts/QuicksandMedium.ttf
          weight: 500
        - asset: assets/fonts/QuicksandRegular.ttf
          weight: 400
        - asset: assets/fonts/QuicksandBold.ttf
          weight: 700